name: Deploy Into Staging Server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Execute remote deployment
        run: sshpass -p '${{ secrets.SSH_PASS }}' ssh -tt -oStrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /var/www/magento2/app/code; git pull origin main;'
